# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_time', models.DateTimeField(auto_now_add=True)),
                ('contact_company', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=20)),
                ('contact_occupation', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_detail', models.TextField(blank=True, max_length=50)),
            ],
        ),
    ]
